name: app_01
description: Flutter UI Kit - Developer Kit

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 17.1.3+26

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^3.1.0
  grpc: ^3.2.4
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  fixnum: ^1.1.0
  audioplayers: 5.2.1
  backdrop: 0.9.1
  badges: 3.1.2
  battery_plus: 4.1.0
  cached_network_image: 3.3.0
  carousel_slider: 4.2.1
  cloud_firestore: 4.13.1
  convex_bottom_bar: 3.2.0
  cupertino_icons: 1.0.6
  date_format: 2.0.7
  device_info_plus: 9.1.0
  dio: 5.3.3
  firebase_auth: 4.14.0
  firebase_storage: 11.5.1
  #flick_video_player: 0.5.0 must wait for the update because not compatible with the new package win32
  fluttertoast: ^8.2.4
  flutter_barcode_scanner: 2.0.0
  barcode_widget: ^2.0.4
  flutter_bloc: 8.1.3
  flutter_html: 3.0.0-beta.2
  flutter_local_notifications: 16.1.0
  flutter_timezone: 1.0.8
  flutter_screenutil: 5.9.0
  flutter_signature_pad: 3.0.1
  flutter_spinkit: 5.2.0
  flutter_staggered_grid_view: 0.7.0
  flutter_typeahead: 4.8.0
  flutter_windowmanager: 0.2.0
  geocoding: 2.1.1
  google_fonts: 6.1.0
  google_maps_flutter: 2.5.0
  google_maps_flutter_web: 0.5.4+2
  google_sign_in: 6.1.6
  image: 4.1.3
  image_cropper: 5.0.0
  image_picker: 1.0.4
  intl: 0.18.1
  like_button: 2.0.5
  package_info_plus: 4.2.0
  path_provider: 2.1.1
  percent_indicator: 4.2.3
  permission_handler: 11.0.1
  # photofilters: 3.0.1 must wait for the update because not compatible with the new package image
  pin_code_fields: 8.0.1
  share_plus: 7.2.1
  shared_preferences: 2.2.2
  shimmer: 3.0.0
  signature: 5.4.0
  sliding_up_panel: 2.0.0+1
  sticky_headers: 0.3.0+2
  syncfusion_flutter_charts: 23.1.36
  timeline_tile: 2.0.0
  universal_io: 2.2.2
  url_launcher: 6.2.1
  uuid: 4.2.1
  video_player: 2.8.1
  visibility_detector: 0.4.0+2
  waterfall_flow: 3.0.2
  webview_flutter: 4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_horizontal.png"
  min_sdk_android: 21
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Audiowide
      fonts:
        - asset: assets/google_fonts/Audiowide-Regular.ttf
    - family: Bariol
      fonts:
        - asset: assets/fonts/Bariol_Regular.otf
        - asset: assets/fonts/Bariol_Thin.otf
          weight: 100
        - asset: assets/fonts/Bariol_Thin_Italic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/Bariol_Light.otf
          weight: 300
        - asset: assets/fonts/Bariol_Light_Italic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Bariol_Bold.otf
          weight: 700

  assets:
    - assets/images/logo_light.png
    - assets/images/logo_dark.png
    - assets/images/logo_horizontal.png
    - assets/images/lamp.jpg
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/twitter.png
    - assets/images/whatsapp.png
    - assets/images/placeholder.jpg
    - assets/images/visa.png
    - assets/images/mastercard.png
    - assets/images/direction.png
    - assets/images/stop.png

    - assets/images/lang/en.png
    - assets/images/lang/id.png
    - assets/images/lang/ar.png
    - assets/images/lang/zh.png
    - assets/images/lang/hi.png
    - assets/images/lang/th.png
    - assets/images/lang/tk.png

    - assets/images/apps/food_delivery/logo.png
    - assets/images/apps/ecommerce/logo.png
    - assets/images/apps/ecommerce/onboarding/search_product.gif
    - assets/images/icon_menu/buy.png
    - assets/images/icon_menu/eco-factory_32.png
    - assets/images/icon_menu/MasterList_32.png
    - assets/images/icon_menu/money-bag_32.png
    - assets/images/icon_menu/setting_32.png
    - assets/images/icon_menu/warehouse_32.png

    - assets/lang/en.json
    - assets/lang/id.json
    - assets/lang/ar.json
    - assets/lang/zh.json
    - assets/lang/hi.json
    - assets/lang/th.json
    - assets/lang/tk.json

    - assets/html/webview.html

    - assets/videos/demo.mp4
    - assets/sounds/demo1.mp3
